package my.rinat.kata.collections.candy;

public enum Candy {
    SNICKERS,
    MILKYWAY,
    REESES_PIECES,
    REESES_PEANUT_BUTTER_CUPS,
    M_AND_M_S,
    TWIZZLERS,
    WHOPPERS,
    ONE_HUNDRED_GRAND,
    SKITTLES,
    TWIX,
    CANDY_CORN,
    JOLLY_RANCHERS,
    NERDS,
    ALMOND_JOY,
    MOUNDS,
    BABY_RUTH,
    THREE_MUSKETEERS,
    HERSHEYS,
    CRUNCH,
    HERSHEYS_KISSES,
    MIKE_AND_IKE,
    MILK_DUDS,
    SWEDISH_FISH,
    YORK_PEPPERMINT_PATTY
}
